apiVersion: v1
kind: Service
metadata:
  name: nexus-feedback-emitter-service
  namespace: camejocristianoorige-dev
spec:
  selector:
    app: nexus-feedback-emitter
  ports:
    - protocol: TCP
      port: 8082      # Porta do Service
      targetPort: 8082 # Porta real do container do Emitter
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nexus-feedback-emitter-route
  namespace: camejocristianoorige-dev
spec:
  to:
    kind: Service
    name: nexus-feedback-emitter-service
  port:
    targetPort: 8082
